CMS_HOST: studio.local.overhang.io
CONTACT_EMAIL: contact@local.overhang.io
DISCOVERY_MYSQL_PASSWORD: IpGIpyhv
DISCOVERY_OAUTH2_SECRET: R4j1kt6b
DISCOVERY_OAUTH2_SECRET_SSO: IPNs8yCz
DISCOVERY_SECRET_KEY: z6Ux54kyLlVxuTNs9DAD
DOCKER_IMAGE_DISCOVERY: docker.io/tauseefchahal/discovery:001
DOCKER_IMAGE_OPENEDX: docker.io/tauseefchahal/openedx:001
EDX_PLATFORM_REPOSITORY: https://github.com/edlywmf/edx-platform.git
EDX_PLATFORM_VERSION: open-release/lilac.master
ENABLE_HTTPS: false
ID: hh6XBSJdukAiJ18t8YrPYJKY
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAx1NhR1c1tOB5wh2zan7LFH4PwMbMUIGoU/8LiejEgaHv2RCU

  Bdw8HpB42qAF/624xxB/l+iDNuMmmucKmuwS+0Rqx+qihT4fT0ud3/QL1Ot68/GH

  NFeQ1LXCEX/XgfmOTdZ/QJ3F1SbCRiNNiL1zNKo1pXjGen1om7mQhjqvwAkn+QYA

  nwqYGOcbOs4Mf/Rb/sJM20SPj5mEDWaYEZRimXUwprU2mmPSKokBIJW0I6RE5b2K

  WRemEavcCgN+dAUwMYyW54DloNO5htH1wcKaXKgMS/lfoz3hSO/PwvDivuACe/dS

  L69vvMamtzMXLQ7mdZTD9zH10cMLqPTgUrW9LQIDAQABAoIBAANPgredHrK84bjU

  JnU32uahu2A/zQfvR1zxyP7G43ClwGaSDGtWf5cgXil/a+oVuBJyVzQuM/O27R64

  hKgTELOkrMNaRc3BvOJjxqEAHCwypw2jLtQzOiAWTr1cqrcpbnAjhmSL2kvSg3qH

  vpNtVhsDUrXHXkCNka24dMqN8fpWBRbXwpOEOw8+ZHqCy0acQHl9lIY4Y/Y/uvi+

  lbqLz8ZCrdrfiNs4fUlc1jKn0mrMRQ5JrL9iF9tuqijXIn6MeOwulPNFFTH14Dmp

  geUTdwoJ5i9wm6O1nvnkFZmwv1zmpeJle0IQJC53Z3QNhZudTzBb4+NJlNtjOj41

  Nan6R/ECgYEA3CxRNhIa5YC9hHFex6PZ9bTS9wz30Oxog+kdfVv0JH2vN7SOcB0r

  hBTNOnl4ogyyn6GSrdUK8Cs5Sm55wbtGNGRfhdImg0aV4eaFBCdq5uth4pigmBNC

  h7RQaXmMtoniRCn1U9VpTSux/JtPwSGt+JUYmVayndYQ020HH87H3VkCgYEA58Kg

  7+FLwUyt1DFwuvIWJXAjxzZjwAQK91QD2S3qBAAmXx83LzRZOreDMxNLYpzWojIA

  /W2gd+w0Vymjh2isSwXa1o6VbJKrZTMAfrHk5y67HYI91QLPF1901TrYdarvNl9T

  zU5Nmnx7V5GavlE/lDs/jE4Sayh6r177imDmP/UCgYABwBRxMpmmI2zeRax0N9g+

  vM5EioTZ01dNXSgP3BBHzfv7nGLZf1HePfAXu+l6mFE/NaCd4yiwGhfdgJ1VLfDz

  76xWuwH1XzVH03ZRPyL5bPudOotkShroS0WsYPv+Y4A5/H9nyDWLGILUuENdDLB+

  XmkQpwDKgm4l0CMTXKh4GQKBgQCbBLgZO50sQlnTIO7CXMMrb4K+8UZvXUTogi3A

  ytFIs8D2xy5mSKGWgMElHLbD0xxNiRzYZsd672djFdrn67+yvsvNz7lq0gAKxL6E

  AAGYEM3fwwoQvLxAafz/00iODDPNLp4jKUkHGFR4ElBrFHVudOLguiffvUeyndmq

  iX35MQKBgQDTkaQLeL2k7O8SAQ2mf91rGkDYGplwu4jmIOMuWPH79iGWKrcX3AZn

  a+GXtjMCKLtFDsSYhHY68btmpd2kVNrj1Tyk6NRmdgrIxSJtUAtZ+jZXEpuGAc2g

  XoG+hlinQAtutKL+v0zbh0qPsvfHbK1nvXZmbjpEa7l1kZPX6KLdpg==

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.overhang.io
MYSQL_ROOT_PASSWORD: TTEpCoFo
OPENEDX_MYSQL_PASSWORD: 1WzWILH8
OPENEDX_SECRET_KEY: rsd855yt9j8JTzh9AZwZfyfu
PLATFORM_NAME: My Test Edx Platform
PLUGINS:
- discovery
